name: PR Agent

# 1. Trigger su apertura, aggiornamento e riapertura di PR verso main
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  run-ai:
    name: Run AI PR Agent
    runs-on: ubuntu-latest

    steps:
      # 2. Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. (Opzionale) Configura Node / Python / Docker se serve
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # 4. Esegui il tuo AI PR Agent
      - name: Run AI PR agent
        uses: your-org/ai-pr-agent-action@v1
        with:
          # qui metti i parametri richiesti dall'action,
          # ad esempio:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # openai_api_key: ${{ secrets.OPENAI_API_KEY }}