name: alfredcohost-user-docs Docs (preview)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install docsify CLI
        run: npm install -g docsify-cli

      - name: Build docs (generate .nojekyll)
        run: echo "" > docs/.nojekyll

      - name: Deploy preview
        uses: peaceiris/actions-gh-pages-preview@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: preview/${{ github.event.pull_request.number }}