name: Docs Preview

# Trigger su pull request verso main
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install docsify CLI
        run: npm install -g docsify-cli

      - name: Generate .nojekyll
        run: echo "" > docs/.nojekyll

      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: preview/${{ github.event.pull_request.number }}
          publish_dir: ./docs